### PR TITLE
fix: link to atas-are-pdas.svg in Token Program lesson

### LINKED ISSUE #230: Broken link to svg in Token Program lesson
The link to an svg is broken in the Token Program course

image

### PR DESCRIPTION
**Pull request by bwnnwtt**
fixes #230

the fix renders the svg correctly in the github preview:
https://github.com/bwnnwtt/solana-course/blob/fix/token-program-lesson/content/token-program.md
image

### CODE REVIEW

**Review by mikemaccana — APPROVED** [review]

**Comment by mikemaccana** [comment]
Oops that was me!

**Comment by bwnnwtt** [comment]
@jamesrp13 i think this needs your approval and merge

**Review by jamesrp13 — APPROVED** [review]

**Comment by jamesrp13** [comment]
@bwnnwtt can you do me a favor and pull from `draft`? I'm seeing changes I don't think I should be seeing and am curious to see if that fixes it

**Comment by bwnnwtt** [comment]
@jamesrp13 i've synced my fork draft branch with the upstream. is that what you're requesting?

**Comment by jamesrp13** [comment]
Oh shoot I meant this for a different PR sorry @bwnnwtt

**Pull request merged**
